services:
  tallo:
    build: .
    container_name: tallo
    restart: unless-stopped
    ports:
      - "5521:3000"  # Map host port 8080 to container port 3000
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000